//! Recursive-descent parser that builds the lossless [`Tree`] from the
//! significant-token stream. It mirrors `waluau-parser`'s grammar (statement
//! forms, expression precedence, type syntax) but produces a concrete tree that
//! keeps comments and original order instead of the compiler AST.
//!
//! Comma-separated lists store only their element nodes; the separators are
//! dropped here and regenerated by the printer, which is what lets the
//! formatter re-wrap them.

use std::mem::discriminant;

use waluau_diagnostics::Diagnostic;
use waluau_lexer::{Span, TokenKind};

use crate::cst::{Comment, Node, SynToken, SyntaxKind, Tree};
use crate::lex::significant_tokens;

/// Parse `source` into a [`SyntaxKind::Root`] tree.
pub fn parse(source: &str) -> Result<Tree, Diagnostic> {
    let stream = significant_tokens(source)?;
    let mut parser = Parser {
        toks: stream.tokens,
        pos: 0,
        trailing_comments: stream.trailing_comments,
    };
    parser.parse_root()
}

struct Parser {
    toks: Vec<SynToken>,
    pos: usize,
    trailing_comments: Vec<Comment>,
}

/// Convenience: a `TokenKind` value used only for discriminant comparison.
fn ident() -> TokenKind {
    TokenKind::Identifier(String::new())
}

impl Parser {
    // ----- cursor helpers -------------------------------------------------

    fn peek(&self) -> Option<&TokenKind> {
        self.toks.get(self.pos).map(|t| &t.kind)
    }

    fn peek_n(&self, n: usize) -> Option<&TokenKind> {
        self.toks.get(self.pos + n).map(|t| &t.kind)
    }

    fn at(&self, kind: &TokenKind) -> bool {
        self.peek()
            .is_some_and(|k| discriminant(k) == discriminant(kind))
    }

    fn at_n(&self, n: usize, kind: &TokenKind) -> bool {
        self.peek_n(n)
            .is_some_and(|k| discriminant(k) == discriminant(kind))
    }

    /// True when the current token is an identifier with the given text (used
    /// for Waluau's contextual keywords: `is`, `const`, `declare`, `type`, …).
    fn at_kw(&self, name: &str) -> bool {
        matches!(self.peek(), Some(TokenKind::Identifier(s)) if s == name)
    }

    fn kw_n(&self, n: usize, name: &str) -> bool {
        matches!(self.peek_n(n), Some(TokenKind::Identifier(s)) if s == name)
    }

    fn eof(&self) -> bool {
        self.pos >= self.toks.len()
    }

    /// Move the current token into `children` and advance.
    fn bump(&mut self, children: &mut Vec<Node>) {
        if let Some(tok) = self.toks.get(self.pos).cloned() {
            children.push(Node::Token(tok));
            self.pos += 1;
        }
    }

    fn eat(&mut self, kind: &TokenKind, children: &mut Vec<Node>) -> bool {
        if self.at(kind) {
            self.bump(children);
            true
        } else {
            false
        }
    }

    fn expect(
        &mut self,
        kind: &TokenKind,
        children: &mut Vec<Node>,
        msg: &str,
    ) -> Result<(), Diagnostic> {
        if self.at(kind) {
            self.bump(children);
            Ok(())
        } else {
            Err(self.error(msg))
        }
    }

    /// Consume a property name. `not` is a keyword in expression position,
    /// but is also the name of the expectation modifier exposed by
    /// `declare property` and used in `value:not:matcher()` chains.
    fn expect_property_name(
        &mut self,
        children: &mut Vec<Node>,
        msg: &str,
    ) -> Result<(), Diagnostic> {
        if self.at(&ident()) || self.at(&TokenKind::Not) {
            self.bump(children);
            Ok(())
        } else {
            Err(self.error(msg))
        }
    }

    fn error(&self, msg: &str) -> Diagnostic {
        Diagnostic::new(format!(
            "formatter parse error: {msg} (at token {})",
            self.toks
                .get(self.pos)
                .map(|t| t.text.as_str())
                .unwrap_or("<eof>")
        ))
    }

    fn tree(kind: SyntaxKind, children: Vec<Node>) -> Node {
        Node::Tree(Tree::new(kind, children))
    }

    // ----- top level ------------------------------------------------------

    fn parse_root(&mut self) -> Result<Tree, Diagnostic> {
        let mut children = Vec::new();
        while !self.eof() {
            // Optional `;` separators are dropped.
            if self.eat(&TokenKind::Semicolon, &mut Vec::new()) {
                continue;
            }
            children.push(self.parse_top_level_item()?);
        }
        // Preserve comments dangling after the last item as a synthetic
        // trailing node the printer can emit.
        if !self.trailing_comments.is_empty() {
            let comments = std::mem::take(&mut self.trailing_comments);
            // Place the synthetic trailer at end-of-source so it sorts after
            // every real item for range queries.
            let eof = self.toks.last().map(|t| t.span.end).unwrap_or(0);
            children.push(Node::Token(SynToken {
                kind: TokenKind::LineComment(String::new()),
                span: Span {
                    start: eof,
                    end: eof,
                },
                text: String::new(),
                leading: comments,
                trailing: None,
                blank_before: true,
            }));
        }
        Ok(Tree::new(SyntaxKind::Root, children))
    }

    fn parse_top_level_item(&mut self) -> Result<Node, Diagnostic> {
        let export_offset = usize::from(self.at_kw("export"));
        if self.kw_n(export_offset, "enum")
            && self.at_n(export_offset + 1, &ident())
            && self.at_n(export_offset + 2, &TokenKind::LBrace)
        {
            return self.parse_enum_decl();
        }
        if self.is_type_decl_start() {
            return self.parse_type_decl();
        }
        if self.at(&TokenKind::Function)
            || (self.at_kw("export") && self.at_n(1, &TokenKind::Function))
        {
            return self.parse_function_decl();
        }
        if self.at_kw("declare") && self.at_n(1, &TokenKind::Function) {
            return self.parse_declare_function();
        }
        if self.at_kw("declare") && self.kw_n(1, "property") {
            return self.parse_declare_property();
        }
        if self.at_kw("declare") && self.kw_n(1, "const") {
            return self.parse_declare_const();
        }
        self.parse_stmt()
    }

    fn parse_enum_decl(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        if self.at_kw("export") {
            self.bump(&mut c);
        }
        self.bump(&mut c); // enum
        self.expect(&ident(), &mut c, "expected enum name")?;
        self.expect(&TokenKind::LBrace, &mut c, "expected '{' after enum name")?;
        while !self.at(&TokenKind::RBrace) && !self.eof() {
            let mut variant = Vec::new();
            self.expect(&ident(), &mut variant, "expected enum variant")?;
            c.push(Self::tree(SyntaxKind::NameExpr, variant));
            if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                break;
            }
        }
        self.expect(
            &TokenKind::RBrace,
            &mut c,
            "expected '}' after enum variants",
        )?;
        Ok(Self::tree(SyntaxKind::EnumDecl, c))
    }

    fn is_type_decl_start(&self) -> bool {
        let offset = usize::from(self.at_kw("export"));
        (self.kw_n(offset, "type")
            && self.at_n(offset + 1, &ident())
            && (self.at_n(offset + 2, &TokenKind::Equal)
                || self.at_n(offset + 2, &TokenKind::Less)))
            || (self.kw_n(offset, "opaque")
                && self.kw_n(offset + 1, "type")
                && self.at_n(offset + 2, &ident())
                && (self.at_n(offset + 3, &TokenKind::Equal)
                    || self.at_n(offset + 3, &TokenKind::Less)))
    }

    fn parse_type_decl(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        if self.at_kw("export") {
            self.bump(&mut c);
        }
        if self.at_kw("opaque") {
            self.bump(&mut c);
        }
        self.bump(&mut c); // `type`
        self.expect(&ident(), &mut c, "expected type name")?;
        if self.at(&TokenKind::Less) {
            c.push(self.parse_type_params()?);
        }
        self.expect(
            &TokenKind::Equal,
            &mut c,
            "expected '=' in type declaration",
        )?;
        let first = self.parse_type()?;
        if self.at(&TokenKind::Ampersand) {
            // Conformance marker: `type Name = Interface & { ... }`.
            let mut k = vec![first];
            self.bump(&mut k); // `&`
            k.push(self.parse_type()?);
            c.push(Self::tree(SyntaxKind::ConformanceType, k));
        } else {
            c.push(first);
        }
        Ok(Self::tree(SyntaxKind::TypeDecl, c))
    }

    fn parse_function_decl(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        if self.at_kw("export") {
            self.bump(&mut c);
        }
        self.bump(&mut c); // `function`
        c.push(self.parse_function_name()?);
        self.parse_function_tail(&mut c, false)?;
        Ok(Self::tree(SyntaxKind::FunctionDecl, c))
    }

    fn parse_function_name(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.expect(&ident(), &mut c, "expected function name")?;
        if self.at(&TokenKind::Colon) || self.at(&TokenKind::Dot) {
            self.bump(&mut c); // `:` or `.`
            self.expect(&ident(), &mut c, "expected name after '.'/':'")?;
        }
        Ok(Self::tree(SyntaxKind::FunctionName, c))
    }

    /// The `<T>? (params) (: rettype)? body end` tail shared by function decls
    /// and function expressions.
    fn parse_function_tail(
        &mut self,
        c: &mut Vec<Node>,
        signature_only: bool,
    ) -> Result<(), Diagnostic> {
        if self.at(&TokenKind::Less) {
            c.push(self.parse_type_params()?);
        }
        c.push(self.parse_param_list()?);
        if self.at(&TokenKind::Colon) {
            let mut rc = Vec::new();
            self.bump(&mut rc); // `:`
            rc.push(self.parse_return_type_list()?);
            c.push(Self::tree(SyntaxKind::ReturnAnnotation, rc));
        }
        if signature_only {
            return Ok(());
        }
        c.push(self.parse_block(&[TokenKind::End])?);
        self.expect(&TokenKind::End, c, "expected 'end' after function body")?;
        Ok(())
    }

    fn parse_param_list(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.expect(&TokenKind::LParen, &mut c, "expected '('")?;
        while !self.at(&TokenKind::RParen) && !self.eof() {
            let mut p = Vec::new();
            if self.at(&TokenKind::TripleDot) {
                self.bump(&mut p);
                if self.eat(&TokenKind::Colon, &mut p) {
                    p.push(self.parse_type()?);
                }
            } else {
                self.expect(&ident(), &mut p, "expected parameter name")?;
                if self.eat(&TokenKind::Colon, &mut p) {
                    p.push(self.parse_type()?);
                }
            }
            c.push(Self::tree(SyntaxKind::Param, p));
            if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                break;
            }
        }
        self.expect(&TokenKind::RParen, &mut c, "expected ')'")?;
        Ok(Self::tree(SyntaxKind::ParamList, c))
    }

    fn parse_declare_function(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `declare`
        self.bump(&mut c); // `function`
        c.push(self.parse_function_name()?);
        self.parse_function_tail(&mut c, true)?;
        Ok(Self::tree(SyntaxKind::DeclareFunction, c))
    }

    fn parse_declare_property(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `declare`
        self.bump(&mut c); // `property`
        self.expect(&ident(), &mut c, "expected property receiver")?;
        self.expect(&TokenKind::Colon, &mut c, "expected ':'")?;
        self.expect_property_name(&mut c, "expected property name")?;
        self.expect(&TokenKind::Colon, &mut c, "expected ':' before type")?;
        c.push(self.parse_type()?);
        Ok(Self::tree(SyntaxKind::DeclareProperty, c))
    }

    fn parse_declare_const(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `declare`
        self.bump(&mut c); // `const`
        self.expect(&ident(), &mut c, "expected namespace")?;
        self.expect(&TokenKind::Dot, &mut c, "expected '.'")?;
        self.expect(&ident(), &mut c, "expected member name")?;
        self.expect(&TokenKind::Colon, &mut c, "expected ':'")?;
        c.push(self.parse_type()?);
        self.expect(&TokenKind::Equal, &mut c, "expected '='")?;
        c.push(self.parse_expr()?);
        Ok(Self::tree(SyntaxKind::DeclareConst, c))
    }

    // ----- statements -----------------------------------------------------

    fn parse_block(&mut self, terminators: &[TokenKind]) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        while !self.eof() {
            if self.eat(&TokenKind::Semicolon, &mut Vec::new()) {
                continue;
            }
            if terminators.iter().any(|t| self.at(t)) {
                break;
            }
            c.push(self.parse_stmt()?);
        }
        Ok(Self::tree(SyntaxKind::Block, c))
    }

    fn parse_stmt(&mut self) -> Result<Node, Diagnostic> {
        if self.at_kw("match") {
            return self.parse_match();
        }
        if self.at(&TokenKind::Local) {
            return self.parse_local();
        }
        if self.is_const_decl_start() {
            return self.parse_const();
        }
        if self.at(&TokenKind::If) {
            return self.parse_if();
        }
        if self.at(&TokenKind::While) {
            return self.parse_while();
        }
        if self.at(&TokenKind::Repeat) {
            return self.parse_repeat();
        }
        if self.at(&TokenKind::For) {
            return self.parse_for();
        }
        if self.at(&TokenKind::Do) {
            return self.parse_do();
        }
        if self.at(&TokenKind::Break) {
            let mut c = Vec::new();
            self.bump(&mut c);
            return Ok(Self::tree(SyntaxKind::BreakStmt, c));
        }
        if self.at(&TokenKind::Continue) {
            let mut c = Vec::new();
            self.bump(&mut c);
            return Ok(Self::tree(SyntaxKind::ContinueStmt, c));
        }
        if self.at(&TokenKind::Return) {
            return self.parse_return();
        }
        self.parse_assign_or_expr()
    }

    fn parse_match(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // match
        c.push(self.parse_expr()?);
        self.expect(&TokenKind::Do, &mut c, "expected 'do' after match value")?;
        while !self.at(&TokenKind::End) && !self.eof() {
            if !self.at_kw("case") {
                return Err(self.error("expected 'case' or 'end' in match"));
            }
            let mut arm = Vec::new();
            self.bump(&mut arm); // case
            let mut pattern = Vec::new();
            self.expect(&ident(), &mut pattern, "expected enum name")?;
            self.expect(&TokenKind::Dot, &mut pattern, "expected '.' in match case")?;
            self.expect(&ident(), &mut pattern, "expected enum name or variant")?;
            if self.at(&TokenKind::Dot) {
                self.bump(&mut pattern);
                self.expect(&ident(), &mut pattern, "expected enum variant")?;
            }
            arm.push(Self::tree(SyntaxKind::FieldExpr, pattern));
            self.expect(
                &TokenKind::Then,
                &mut arm,
                "expected 'then' after match case",
            )?;
            let mut body = Vec::new();
            while !self.at(&TokenKind::End) && !self.at_kw("case") && !self.eof() {
                body.push(self.parse_stmt()?);
            }
            arm.push(Self::tree(SyntaxKind::Block, body));
            c.push(Self::tree(SyntaxKind::MatchArm, arm));
        }
        self.expect(&TokenKind::End, &mut c, "expected 'end' after match")?;
        Ok(Self::tree(SyntaxKind::MatchStmt, c))
    }

    fn parse_local(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `local`
        if self.at(&TokenKind::Function) {
            // `local function f() ... end`
            self.bump(&mut c); // `function`
            self.expect(&ident(), &mut c, "expected function name")?;
            self.parse_function_tail(&mut c, false)?;
            return Ok(Self::tree(SyntaxKind::LetStmt, c));
        }
        c.push(self.parse_binding_list()?);
        if self.eat(&TokenKind::Equal, &mut c) {
            c.push(self.parse_expr_list()?);
        }
        Ok(Self::tree(SyntaxKind::LetStmt, c))
    }

    fn is_const_decl_start(&self) -> bool {
        self.at_kw("const") && (self.at_n(1, &ident()) || self.at_n(1, &TokenKind::Function))
    }

    fn parse_const(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `const`
        if self.at(&TokenKind::Function) {
            self.bump(&mut c);
            self.expect(&ident(), &mut c, "expected function name")?;
            self.parse_function_tail(&mut c, false)?;
            return Ok(Self::tree(SyntaxKind::ConstStmt, c));
        }
        c.push(self.parse_binding_list()?);
        self.expect(
            &TokenKind::Equal,
            &mut c,
            "expected '=' in const declaration",
        )?;
        c.push(self.parse_expr_list()?);
        Ok(Self::tree(SyntaxKind::ConstStmt, c))
    }

    fn parse_binding_list(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        loop {
            c.push(self.parse_binding()?);
            if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                break;
            }
        }
        Ok(Self::tree(SyntaxKind::BindingList, c))
    }

    fn parse_binding(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.expect(&ident(), &mut c, "expected binding name")?;
        if self.at(&TokenKind::Less) {
            let mut a = Vec::new();
            self.bump(&mut a); // `<`
            self.expect(&ident(), &mut a, "expected attribute")?;
            self.expect_greater(&mut a, "expected '>' after attribute")?;
            c.push(Self::tree(SyntaxKind::Attribute, a));
        }
        if self.eat(&TokenKind::Colon, &mut c) {
            c.push(self.parse_type()?);
        }
        Ok(Self::tree(SyntaxKind::Binding, c))
    }

    fn parse_if(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `if`
        c.push(self.parse_if_clause()?);
        self.expect(&TokenKind::End, &mut c, "expected 'end' after if")?;
        Ok(Self::tree(SyntaxKind::IfStmt, c))
    }

    fn parse_if_clause(&mut self) -> Result<Node, Diagnostic> {
        // Type-narrowing form: `Name(binding) = value then`, where the
        // target may be module-qualified (`ops.Add`).
        let dotted = self.at(&ident()) && self.at_n(1, &TokenKind::Dot) && self.at_n(2, &ident());
        let name_tokens = if dotted { 3 } else { 1 };
        if self.at(&ident())
            && self.at_n(name_tokens, &TokenKind::LParen)
            && self.at_n(name_tokens + 1, &ident())
            && self.at_n(name_tokens + 2, &TokenKind::RParen)
            && self.at_n(name_tokens + 3, &TokenKind::Equal)
        {
            let mut c = Vec::new();
            self.bump(&mut c); // target name
            if dotted {
                self.bump(&mut c); // `.`
                self.bump(&mut c); // member
            }
            self.bump(&mut c); // (
            self.bump(&mut c); // binding
            self.bump(&mut c); // )
            self.eat(&TokenKind::Equal, &mut Vec::new()); // `=` regenerated by printer
            c.push(self.parse_expr()?);
            self.expect(&TokenKind::Then, &mut c, "expected 'then'")?;
            c.push(self.parse_block(&[TokenKind::ElseIf, TokenKind::Else, TokenKind::End])?);
            self.parse_if_tail(&mut c)?;
            return Ok(Self::tree(SyntaxKind::IfCastClause, c));
        }

        let mut c = Vec::new();
        c.push(self.parse_expr()?);
        self.expect(&TokenKind::Then, &mut c, "expected 'then' after condition")?;
        c.push(self.parse_block(&[TokenKind::ElseIf, TokenKind::Else, TokenKind::End])?);
        self.parse_if_tail(&mut c)?;
        Ok(Self::tree(SyntaxKind::IfClause, c))
    }

    fn parse_if_tail(&mut self, c: &mut Vec<Node>) -> Result<(), Diagnostic> {
        if self.at(&TokenKind::ElseIf) {
            self.bump(c); // `elseif`
            c.push(self.parse_if_clause()?);
        } else if self.at(&TokenKind::Else) {
            self.bump(c); // `else`
            c.push(self.parse_block(&[TokenKind::End])?);
        }
        Ok(())
    }

    fn parse_while(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `while`
        c.push(self.parse_expr()?);
        self.expect(&TokenKind::Do, &mut c, "expected 'do'")?;
        c.push(self.parse_block(&[TokenKind::End])?);
        self.expect(&TokenKind::End, &mut c, "expected 'end'")?;
        Ok(Self::tree(SyntaxKind::WhileStmt, c))
    }

    fn parse_repeat(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `repeat`
        c.push(self.parse_block(&[TokenKind::Until])?);
        self.expect(&TokenKind::Until, &mut c, "expected 'until'")?;
        c.push(self.parse_expr()?);
        Ok(Self::tree(SyntaxKind::RepeatStmt, c))
    }

    fn parse_for(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `for`
        self.expect(&ident(), &mut c, "expected loop variable")?;
        if self.at(&TokenKind::Equal) {
            // Commas between range expressions are dropped and regenerated.
            self.bump(&mut c); // `=`
            c.push(self.parse_expr()?); // start
            self.expect(
                &TokenKind::Comma,
                &mut Vec::new(),
                "expected ',' after for start",
            )?;
            c.push(self.parse_expr()?); // stop
            if self.eat(&TokenKind::Comma, &mut Vec::new()) {
                c.push(self.parse_expr()?); // step
            }
            self.expect(&TokenKind::Do, &mut c, "expected 'do'")?;
            c.push(self.parse_block(&[TokenKind::End])?);
            self.expect(&TokenKind::End, &mut c, "expected 'end'")?;
            return Ok(Self::tree(SyntaxKind::NumericForStmt, c));
        }
        // Generic `for a, b in iter do`. Commas between names are dropped.
        while self.eat(&TokenKind::Comma, &mut Vec::new()) {
            self.expect(&ident(), &mut c, "expected loop variable")?;
        }
        self.expect(&TokenKind::In, &mut c, "expected 'in'")?;
        // The generic-for protocol takes an expression list:
        // `iterator, state[, control]`. Commas are dropped and regenerated.
        c.push(self.parse_expr()?);
        while self.eat(&TokenKind::Comma, &mut Vec::new()) {
            c.push(self.parse_expr()?);
        }
        self.expect(&TokenKind::Do, &mut c, "expected 'do'")?;
        c.push(self.parse_block(&[TokenKind::End])?);
        self.expect(&TokenKind::End, &mut c, "expected 'end'")?;
        Ok(Self::tree(SyntaxKind::ForInStmt, c))
    }

    fn parse_do(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `do`
        c.push(self.parse_block(&[TokenKind::End])?);
        self.expect(&TokenKind::End, &mut c, "expected 'end'")?;
        Ok(Self::tree(SyntaxKind::DoStmt, c))
    }

    fn parse_return(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `return`
        if !self.eof()
            && !self.at(&TokenKind::End)
            && !self.at(&TokenKind::ElseIf)
            && !self.at(&TokenKind::Else)
            && !self.at(&TokenKind::Until)
            && !self.at(&TokenKind::Semicolon)
        {
            c.push(self.parse_expr_list()?);
        }
        Ok(Self::tree(SyntaxKind::ReturnStmt, c))
    }

    fn parse_assign_or_expr(&mut self) -> Result<Node, Diagnostic> {
        let checkpoint = self.pos;
        let mut targets = vec![self.parse_postfix_expr()?];
        while self.eat(&TokenKind::Comma, &mut Vec::new()) {
            targets.push(self.parse_postfix_expr()?);
        }
        if self.at_assign_op() {
            // AssignStmt = [TargetList, opToken, ValueList].
            let mut c = vec![Self::tree(SyntaxKind::ExprList, targets)];
            self.bump(&mut c); // assignment operator token
            c.push(self.parse_expr_list()?);
            return Ok(Self::tree(SyntaxKind::AssignStmt, c));
        }
        // Not an assignment: re-parse as a single expression statement.
        self.pos = checkpoint;
        let expr = self.parse_expr()?;
        Ok(Self::tree(SyntaxKind::ExprStmt, vec![expr]))
    }

    fn at_assign_op(&self) -> bool {
        matches!(
            self.peek(),
            Some(
                TokenKind::Equal
                    | TokenKind::PlusEqual
                    | TokenKind::MinusEqual
                    | TokenKind::StarEqual
                    | TokenKind::SlashEqual
                    | TokenKind::DoubleSlashEqual
                    | TokenKind::PercentEqual
                    | TokenKind::CaretEqual
                    | TokenKind::DoubleDotEqual
            )
        )
    }

    fn parse_expr_list(&mut self) -> Result<Node, Diagnostic> {
        let mut c = vec![self.parse_expr()?];
        while self.eat(&TokenKind::Comma, &mut Vec::new()) {
            c.push(self.parse_expr()?);
        }
        Ok(Self::tree(SyntaxKind::ExprList, c))
    }

    // ----- expressions ----------------------------------------------------

    fn parse_expr(&mut self) -> Result<Node, Diagnostic> {
        if self.at(&TokenKind::If) {
            return self.parse_if_expr();
        }
        self.parse_binary(0)
    }

    fn parse_if_expr(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `if`
        self.parse_if_expr_clause(c)
    }

    /// Parse an if-expression clause whose leading `if` or `elseif` token is
    /// already in `c`. Chained clauses form nested `IfExpr` CST nodes so token
    /// provenance and comments stay attached to the exact clause they precede.
    fn parse_if_expr_clause(&mut self, mut c: Vec<Node>) -> Result<Node, Diagnostic> {
        c.push(self.parse_expr()?);
        self.expect(&TokenKind::Then, &mut c, "expected 'then'")?;
        c.push(self.parse_expr()?);
        if self.at(&TokenKind::ElseIf) {
            let mut elseif = Vec::new();
            self.bump(&mut elseif);
            c.push(self.parse_if_expr_clause(elseif)?);
        } else {
            self.expect(
                &TokenKind::Else,
                &mut c,
                "expected 'else' or 'elseif' in if-expression",
            )?;
            c.push(self.parse_expr()?);
        }
        Ok(Self::tree(SyntaxKind::IfExpr, c))
    }

    /// Precedence-climbing over the binary levels. `min` is the lowest binding
    /// power still accepted. Levels (low→high): or, and, comparison/`is`,
    /// concat, add, mul. Cast, unary, and pow are handled below the loop.
    fn parse_binary(&mut self, min: u8) -> Result<Node, Diagnostic> {
        let mut left = self.parse_cast()?;
        loop {
            // `is Tag` sits at the comparison level.
            if binding_power_is() >= min && self.at_kw("is") {
                let mut c = vec![left];
                self.bump(&mut c); // `is`
                self.expect(&ident(), &mut c, "expected variant tag after 'is'")?;
                left = Self::tree(SyntaxKind::IsExpr, c);
                continue;
            }
            let Some(bp) = self.peek().and_then(binary_binding_power) else {
                break;
            };
            if bp < min {
                break;
            }
            let mut c = vec![left];
            self.bump(&mut c); // operator
            // Left-associative: parse the right side at bp + 1.
            c.push(self.parse_binary(bp + 1)?);
            left = Self::tree(SyntaxKind::BinaryExpr, c);
        }
        Ok(left)
    }

    fn parse_cast(&mut self) -> Result<Node, Diagnostic> {
        let mut expr = self.parse_unary()?;
        while self.at(&TokenKind::ColonColon) {
            let mut c = vec![expr];
            self.bump(&mut c); // `::`
            c.push(self.parse_type()?);
            expr = Self::tree(SyntaxKind::CastExpr, c);
        }
        Ok(expr)
    }

    fn parse_unary(&mut self) -> Result<Node, Diagnostic> {
        if self.at(&TokenKind::Minus) || self.at(&TokenKind::Not) || self.at(&TokenKind::Hash) {
            let mut c = Vec::new();
            self.bump(&mut c); // unary operator
            c.push(self.parse_unary()?);
            return Ok(Self::tree(SyntaxKind::UnaryExpr, c));
        }
        self.parse_pow()
    }

    fn parse_pow(&mut self) -> Result<Node, Diagnostic> {
        let base = self.parse_postfix_expr()?;
        if self.at(&TokenKind::Caret) {
            let mut c = vec![base];
            self.bump(&mut c); // `^`
            c.push(self.parse_unary()?); // right-assoc, allows `2 ^ -3`
            return Ok(Self::tree(SyntaxKind::BinaryExpr, c));
        }
        Ok(base)
    }

    fn parse_postfix_expr(&mut self) -> Result<Node, Diagnostic> {
        let mut expr = self.parse_primary()?;
        loop {
            if self.at(&TokenKind::Dot) {
                let mut c = vec![expr];
                self.bump(&mut c); // `.`
                self.expect(&ident(), &mut c, "expected field name")?;
                expr = Self::tree(SyntaxKind::FieldExpr, c);
                continue;
            }
            if self.at(&TokenKind::LBracket) {
                let mut c = vec![expr];
                self.bump(&mut c); // `[`
                c.push(self.parse_expr()?);
                self.expect(&TokenKind::RBracket, &mut c, "expected ']'")?;
                expr = Self::tree(SyntaxKind::IndexExpr, c);
                continue;
            }
            if self.at(&TokenKind::Colon) && self.at_n(1, &TokenKind::Not) {
                let mut c = vec![expr];
                self.bump(&mut c); // `:`
                self.bump(&mut c); // `not`
                expr = Self::tree(SyntaxKind::FieldExpr, c);
                continue;
            }
            if self.at_method_call() {
                let mut c = vec![expr];
                self.bump(&mut c); // `:`
                self.expect(&ident(), &mut c, "expected method name")?;
                if let Some(targs) = self.try_type_args()? {
                    c.push(targs);
                }
                c.push(self.parse_call_args()?);
                expr = Self::tree(SyntaxKind::MethodCallExpr, c);
                continue;
            }
            let type_args = self.try_type_args()?;
            if self.at_call_args() {
                let mut c = vec![expr];
                if let Some(targs) = type_args {
                    c.push(targs);
                }
                c.push(self.parse_call_args()?);
                expr = Self::tree(SyntaxKind::CallExpr, c);
                continue;
            }
            if type_args.is_some() {
                return Err(self.error("type arguments must precede a call"));
            }
            break;
        }
        Ok(expr)
    }

    fn at_method_call(&self) -> bool {
        self.at(&TokenKind::Colon)
            && self.at_n(1, &ident())
            && matches!(
                self.peek_n(2),
                Some(TokenKind::LParen | TokenKind::Less | TokenKind::Str(_) | TokenKind::LBrace)
            )
    }

    fn at_call_args(&self) -> bool {
        matches!(
            self.peek(),
            Some(
                TokenKind::LParen
                    | TokenKind::Str(_)
                    | TokenKind::LBrace
                    | TokenKind::InterpString(_)
            )
        )
    }

    fn parse_call_args(&mut self) -> Result<Node, Diagnostic> {
        // Sugar: a single string or table constructor without parentheses.
        if matches!(
            self.peek(),
            Some(TokenKind::Str(_) | TokenKind::InterpString(_))
        ) {
            let mut c = Vec::new();
            self.bump(&mut c);
            return Ok(Self::tree(SyntaxKind::ArgList, c));
        }
        if self.at(&TokenKind::LBrace) {
            let c = vec![self.parse_primary()?];
            return Ok(Self::tree(SyntaxKind::ArgList, c));
        }
        let mut c = Vec::new();
        self.expect(&TokenKind::LParen, &mut c, "expected '('")?;
        while !self.at(&TokenKind::RParen) && !self.eof() {
            c.push(self.parse_expr()?);
            if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                break;
            }
        }
        self.expect(&TokenKind::RParen, &mut c, "expected ')' after arguments")?;
        Ok(Self::tree(SyntaxKind::ArgList, c))
    }

    /// Attempt to parse `<T, ...>` type arguments, but only commit if a call
    /// argument list follows (otherwise `<` is a comparison operator).
    fn try_type_args(&mut self) -> Result<Option<Node>, Diagnostic> {
        if !self.at(&TokenKind::Less) {
            return Ok(None);
        }
        let checkpoint = self.pos;
        let mut c = Vec::new();
        self.bump(&mut c); // `<`
        if self.at(&TokenKind::Greater) || self.at(&TokenKind::GreaterEqual) {
            self.pos = checkpoint;
            return Ok(None);
        }
        loop {
            match self.parse_type() {
                Ok(ty) => c.push(ty),
                Err(_) => {
                    self.pos = checkpoint;
                    return Ok(None);
                }
            }
            if self.eat(&TokenKind::Comma, &mut Vec::new()) {
                continue;
            }
            if self.at(&TokenKind::Greater) || self.at(&TokenKind::GreaterEqual) {
                self.expect_greater(&mut c, "expected '>'")?;
                break;
            }
            self.pos = checkpoint;
            return Ok(None);
        }
        if self.at_call_args() {
            Ok(Some(Self::tree(SyntaxKind::TypeArgs, c)))
        } else {
            self.pos = checkpoint;
            Ok(None)
        }
    }

    fn parse_primary(&mut self) -> Result<Node, Diagnostic> {
        match self.peek() {
            Some(
                TokenKind::Number(_)
                | TokenKind::True
                | TokenKind::False
                | TokenKind::Nil
                | TokenKind::Str(_)
                | TokenKind::Bytes(_)
                | TokenKind::InterpString(_),
            ) => {
                let mut c = Vec::new();
                self.bump(&mut c);
                Ok(Self::tree(SyntaxKind::LiteralExpr, c))
            }
            // `string` is a type keyword that doubles as a namespace name.
            Some(TokenKind::Identifier(_) | TokenKind::StringType) => {
                let mut c = Vec::new();
                self.bump(&mut c);
                Ok(Self::tree(SyntaxKind::NameExpr, c))
            }
            Some(TokenKind::TripleDot) => {
                let mut c = Vec::new();
                self.bump(&mut c);
                Ok(Self::tree(SyntaxKind::VarargExpr, c))
            }
            Some(TokenKind::If) => self.parse_if_expr(),
            Some(TokenKind::Function) => self.parse_function_expr(),
            Some(TokenKind::LBrace) => self.parse_brace(),
            Some(TokenKind::LParen) => {
                let mut c = Vec::new();
                self.bump(&mut c); // `(`
                c.push(self.parse_expr()?);
                self.expect(&TokenKind::RParen, &mut c, "expected ')'")?;
                Ok(Self::tree(SyntaxKind::ParenExpr, c))
            }
            _ => Err(self.error("expected expression")),
        }
    }

    fn parse_function_expr(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.bump(&mut c); // `function`
        // Optional name before the parameter list.
        if self.at(&ident()) && (self.at_n(1, &TokenKind::LParen) || self.at_n(1, &TokenKind::Less))
        {
            self.bump(&mut c);
        }
        self.parse_function_tail(&mut c, false)?;
        Ok(Self::tree(SyntaxKind::FunctionExpr, c))
    }

    fn parse_brace(&mut self) -> Result<Node, Diagnostic> {
        // Table literal when it starts with `ident =`, else an array literal.
        let is_table = self.at_n(1, &ident()) && self.at_n(2, &TokenKind::Equal);
        let mut c = Vec::new();
        self.expect(&TokenKind::LBrace, &mut c, "expected '{'")?;
        if is_table {
            while !self.at(&TokenKind::RBrace) && !self.eof() {
                let mut f = Vec::new();
                self.expect(&ident(), &mut f, "expected field name")?;
                self.expect(&TokenKind::Equal, &mut f, "expected '=' in table field")?;
                f.push(self.parse_expr()?);
                c.push(Self::tree(SyntaxKind::TableField, f));
                if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                    break;
                }
            }
            self.expect(&TokenKind::RBrace, &mut c, "expected '}'")?;
            return Ok(Self::tree(SyntaxKind::TableLiteral, c));
        }
        while !self.at(&TokenKind::RBrace) && !self.eof() {
            c.push(self.parse_expr()?);
            if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                break;
            }
        }
        self.expect(&TokenKind::RBrace, &mut c, "expected '}'")?;
        Ok(Self::tree(SyntaxKind::ArrayLiteral, c))
    }

    // ----- types ----------------------------------------------------------

    fn parse_type_params(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.expect(&TokenKind::Less, &mut c, "expected '<'")?;
        if !self.at(&TokenKind::Greater) && !self.at(&TokenKind::GreaterEqual) {
            loop {
                let mut p = Vec::new();
                self.expect(&ident(), &mut p, "expected type parameter")?;
                c.push(Self::tree(SyntaxKind::NamedType, p));
                if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                    break;
                }
            }
        }
        self.expect_greater(&mut c, "expected '>' after type parameters")?;
        Ok(Self::tree(SyntaxKind::TypeParams, c))
    }

    fn parse_return_type_list(&mut self) -> Result<Node, Diagnostic> {
        let first = self.parse_type()?;
        if !self.at(&TokenKind::Comma) {
            return Ok(first);
        }
        let mut c = vec![first];
        while self.eat(&TokenKind::Comma, &mut Vec::new()) {
            c.push(self.parse_type()?);
        }
        Ok(Self::tree(SyntaxKind::TypeList, c))
    }

    fn parse_type(&mut self) -> Result<Node, Diagnostic> {
        let first = self.parse_nullable_type()?;
        if !self.at(&TokenKind::Pipe) {
            return Ok(first);
        }
        let mut c = vec![first];
        while self.eat(&TokenKind::Pipe, &mut Vec::new()) {
            c.push(self.parse_nullable_type()?);
        }
        Ok(Self::tree(SyntaxKind::TaggedUnionType, c))
    }

    fn parse_nullable_type(&mut self) -> Result<Node, Diagnostic> {
        let mut ty = self.parse_type_atom()?;
        while self.at(&TokenKind::Question) {
            let mut c = vec![ty];
            self.bump(&mut c); // `?`
            ty = Self::tree(SyntaxKind::NullableType, c);
        }
        Ok(ty)
    }

    fn parse_type_atom(&mut self) -> Result<Node, Diagnostic> {
        if self.at(&TokenKind::LBrace) {
            let is_record = self.at_n(1, &ident()) && self.at_n(2, &TokenKind::Colon);
            let mut c = Vec::new();
            self.bump(&mut c); // `{`
            // `{}` is the empty record type; `{T}` stays an array type.
            if self.at(&TokenKind::RBrace) {
                self.expect(&TokenKind::RBrace, &mut c, "expected '}'")?;
                return Ok(Self::tree(SyntaxKind::RecordType, c));
            }
            if is_record {
                while !self.at(&TokenKind::RBrace) && !self.eof() {
                    let mut f = Vec::new();
                    self.expect(&ident(), &mut f, "expected record field")?;
                    self.expect(&TokenKind::Colon, &mut f, "expected ':'")?;
                    f.push(self.parse_type()?);
                    c.push(Self::tree(SyntaxKind::RecordField, f));
                    if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                        break;
                    }
                }
                self.expect(&TokenKind::RBrace, &mut c, "expected '}'")?;
                return Ok(Self::tree(SyntaxKind::RecordType, c));
            }
            c.push(self.parse_type()?);
            self.expect(&TokenKind::RBrace, &mut c, "expected '}'")?;
            return Ok(Self::tree(SyntaxKind::ArrayType, c));
        }
        if self.at(&TokenKind::LParen) {
            return self.parse_paren_or_function_type();
        }
        // Primitive type keywords.
        if matches!(
            self.peek(),
            Some(
                TokenKind::NumberType
                    | TokenKind::U32Type
                    | TokenKind::U64Type
                    | TokenKind::I32Type
                    | TokenKind::I64Type
                    | TokenKind::F32Type
                    | TokenKind::F64Type
                    | TokenKind::UnitType
                    | TokenKind::BoolType
                    | TokenKind::StringType
                    | TokenKind::BytesType
                    | TokenKind::ThreadType
                    | TokenKind::UnknownType
            )
        ) {
            let mut c = Vec::new();
            self.bump(&mut c);
            return Ok(Self::tree(SyntaxKind::PrimitiveType, c));
        }
        if self.at(&TokenKind::ExternType) {
            let mut c = Vec::new();
            self.bump(&mut c); // `extern`
            if self.at_kw("extends") {
                self.bump(&mut c); // `extends`
                c.push(self.parse_type()?);
            }
            return Ok(Self::tree(SyntaxKind::PrimitiveType, c));
        }
        // Literal union members: a string literal in type position.
        if matches!(self.peek(), Some(TokenKind::Str(_))) {
            let mut c = Vec::new();
            self.bump(&mut c);
            return Ok(Self::tree(SyntaxKind::LiteralType, c));
        }
        if self.at(&ident()) {
            // Tagged variant `Tag(T)`.
            if self.at_n(1, &TokenKind::LParen) {
                let mut c = Vec::new();
                self.bump(&mut c); // tag
                self.bump(&mut c); // `(`
                c.push(self.parse_type()?);
                self.expect(&TokenKind::RParen, &mut c, "expected ')'")?;
                return Ok(Self::tree(SyntaxKind::TaggedVariantType, c));
            }
            // Named type, possibly dotted, possibly with `<...>` args.
            let mut c = Vec::new();
            self.bump(&mut c); // name
            if self.eat(&TokenKind::Dot, &mut c) {
                self.expect(&ident(), &mut c, "expected member name")?;
            }
            if self.at(&TokenKind::Less) {
                c.push(self.parse_type_arg_list()?);
            }
            return Ok(Self::tree(SyntaxKind::NamedType, c));
        }
        Err(self.error("expected a type"))
    }

    fn parse_paren_or_function_type(&mut self) -> Result<Node, Diagnostic> {
        // Parentheses and commas are dropped and regenerated by the printer.
        self.expect(&TokenKind::LParen, &mut Vec::new(), "expected '('")?;
        let mut inner = Vec::new();
        if !self.at(&TokenKind::RParen) {
            loop {
                // A documentation-only named parameter (`a: i32`). The `self`
                // receiver placeholder needs no special casing here: it is a
                // bare identifier and round-trips as a named type.
                if self.at(&ident()) && self.at_n(1, &TokenKind::Colon) {
                    let mut p = Vec::new();
                    self.bump(&mut p); // name
                    self.bump(&mut p); // `:`
                    p.push(self.parse_type()?);
                    inner.push(Self::tree(SyntaxKind::NamedParamType, p));
                } else {
                    inner.push(self.parse_type()?);
                }
                if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                    break;
                }
            }
        }
        self.expect(&TokenKind::RParen, &mut Vec::new(), "expected ')'")?;
        if self.eat(&TokenKind::Arrow, &mut Vec::new()) {
            // FunctionType = [TypeList(params), returnType].
            let params = Self::tree(SyntaxKind::TypeList, inner);
            // Function types have one bare return type; multiple returns must
            // be parenthesized. Comma-separated bare return lists are only
            // valid on function declarations.
            let ret = self.parse_type()?;
            return Ok(Self::tree(SyntaxKind::FunctionType, vec![params, ret]));
        }
        // Parenthesised grouping (`(T)`) or unit (`()`): inner types only.
        Ok(Self::tree(SyntaxKind::ParenType, inner))
    }

    fn parse_type_arg_list(&mut self) -> Result<Node, Diagnostic> {
        let mut c = Vec::new();
        self.expect(&TokenKind::Less, &mut c, "expected '<'")?;
        if !self.at(&TokenKind::Greater) && !self.at(&TokenKind::GreaterEqual) {
            loop {
                c.push(self.parse_type()?);
                if !self.eat(&TokenKind::Comma, &mut Vec::new()) {
                    break;
                }
            }
        }
        self.expect_greater(&mut c, "expected '>' after type arguments")?;
        Ok(Self::tree(SyntaxKind::TypeArgs, c))
    }

    /// Consume a `>` that closes a type list. A greedily-lexed `>=` is split:
    /// its `>` half closes the list and an `=` token is left in the stream.
    fn expect_greater(&mut self, children: &mut Vec<Node>, msg: &str) -> Result<(), Diagnostic> {
        if self.at(&TokenKind::Greater) {
            self.bump(children);
            return Ok(());
        }
        if self.at(&TokenKind::GreaterEqual) {
            // Rewrite the current token to `=` and treat the `>` as consumed,
            // splitting the `>=` span between the two halves.
            let gt_start = self.toks[self.pos].span.start;
            let tok = &mut self.toks[self.pos];
            tok.kind = TokenKind::Equal;
            tok.text = "=".to_string();
            tok.span.start += 1;
            children.push(Node::Token(SynToken {
                kind: TokenKind::Greater,
                span: Span {
                    start: gt_start,
                    end: gt_start + 1,
                },
                text: ">".to_string(),
                leading: Vec::new(),
                trailing: None,
                blank_before: false,
            }));
            return Ok(());
        }
        Err(self.error(msg))
    }
}

/// Binding power of binary operators, low → high. Mirrors the reference
/// precedence: or < and < comparison < concat < add < mul.
fn binary_binding_power(kind: &TokenKind) -> Option<u8> {
    Some(match kind {
        TokenKind::Or => 1,
        TokenKind::And => 2,
        TokenKind::EqualEqual
        | TokenKind::TildeEqual
        | TokenKind::Less
        | TokenKind::LessEqual
        | TokenKind::Greater
        | TokenKind::GreaterEqual => 3,
        TokenKind::DoubleDot => 4,
        TokenKind::Plus | TokenKind::Minus => 5,
        TokenKind::Star | TokenKind::Slash | TokenKind::DoubleSlash | TokenKind::Percent => 6,
        _ => return None,
    })
}

/// `is Tag` binds at the comparison level.
fn binding_power_is() -> u8 {
    3
}
