name = "Waluau"
grammar = "waluau"
path_suffixes = ["walu"]
line_comments = ["-- "]
block_comment = ["--[[", "]]"]
autoclose_before = ";:.,=}])>"
tab_size = 4
hard_tabs = false
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = false, not_in = ["comment", "string"] },
    { start = "then", end = "end", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "do", end = "end", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "function", end = "end", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "repeat", end = "until", close = false, newline = true, not_in = ["comment", "string"] },
]
